[project]
name = "entrez-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "biopython>=1.85",
    "great-tables>=0.16.1",
    "marimo>=0.11.17",
    "numpy>=2.2.3",
    "polars>=1.24.0",
]
